/**
 * Setup Wizard Tests — TDD RED Phase
 *
 * Tests the non-interactive mode of the setup wizard script.
 * Validates .env file generation with correct configuration.
 *
 * Constitution: TS-9 (test real code), TS-12 (>=5 cases)
 */
import { describe, it, expect, afterEach } from 'vitest';
import { execSync, ExecSyncOptions, spawnSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { parse as parseJsoncValue } from 'jsonc-parser';

const EXEC_OPTS: ExecSyncOptions = { stdio: 'pipe', timeout: 60_000 };
// Runtime deploy invokes nested `npm install` inside a temp dir. The wizard itself
// budgets 420s on Windows for that nested install (see setup-wizard.mjs); the outer
// execSync timeout must comfortably exceed that to avoid spawnSync ETIMEDOUT on
// slow Windows GitHub runners. Linux runners are dramatically faster, so a smaller
// budget is fine there.
const IS_WINDOWS = process.platform === 'win32';
const DEPLOY_EXEC_OPTS: ExecSyncOptions = {
  stdio: 'pipe',
  timeout: IS_WINDOWS ? 600_000 : 180_000,
};
const DEPLOY_TEST_TIMEOUT_MS = IS_WINDOWS ? 720_000 : 240_000;
const ROOT = path.resolve(__dirname, '..', '..');
const WIZARD_SCRIPT = path.join(ROOT, 'scripts', 'build', 'setup-wizard.mjs');

function hasOpenSsl(): boolean {
  try {
    execSync('openssl version', { stdio: 'pipe' });
    return true;
  } catch {
    if (process.platform !== 'win32') return false;
    const gitSslDir = 'C:\\Program Files\\Git\\usr\\bin';
    if (!fs.existsSync(path.join(gitSslDir, 'openssl.exe'))) return false;
    process.env.PATH = `${gitSslDir}${path.delimiter}${process.env.PATH}`;
    return true;
  }
}

function runWizard(args: string, opts?: ExecSyncOptions): string {
  return execSync(
    `node "${WIZARD_SCRIPT}" --non-interactive ${args}`,
    { ...EXEC_OPTS, ...opts, cwd: ROOT, env: { ...process.env, HOME: os.tmpdir(), USERPROFILE: os.tmpdir() } }
  ).toString();
}

function readGeneratedEnv(): string {
  // Wizard writes to .env or .env.generated
  const envPath = path.join(ROOT, '.env.generated');
  const mainPath = path.join(ROOT, '.env');
  if (fs.existsSync(envPath)) return fs.readFileSync(envPath, 'utf8');
  if (fs.existsSync(mainPath)) return fs.readFileSync(mainPath, 'utf8');
  return '';
}

function parseJsonc(text: string): unknown {
  return parseJsoncValue(text);
}

describe('Setup Wizard Non-Interactive Mode', () => {
  afterEach(() => {
    // Cleanup generated files
    try { fs.unlinkSync(path.join(ROOT, '.env.generated')); } catch { /* ok */ }
  });

  it('should generate .env file with default settings', () => {
    runWizard('');
    const env = readGeneratedEnv();
    expect(env).toContain('INDEX_SERVER_DASHBOARD=1');
    expect(env).toContain('INDEX_SERVER_DASHBOARD_PORT=8787');
    expect(env).toContain('INDEX_SERVER_MUTATION=1');
  });

  it('should respect --port flag', () => {
    runWizard('--port 9999');
    const env = readGeneratedEnv();
    expect(env).toContain('INDEX_SERVER_DASHBOARD_PORT=9999');
  });

  it('should enable TLS when --tls flag is set', () => {
    runWizard('--tls');
    const env = readGeneratedEnv();
    expect(env).toContain('INDEX_SERVER_DASHBOARD_TLS=1');
    expect(env).toContain('INDEX_SERVER_DASHBOARD_TLS_CERT=');
    expect(env).toContain('INDEX_SERVER_DASHBOARD_TLS_KEY=');
  });

  it('should enable mutation when --mutation flag is set', () => {
    runWizard('--mutation');
    const env = readGeneratedEnv();
    expect(env).toContain('INDEX_SERVER_MUTATION=1');
  });

  it('should set log level when --log-level is specified', () => {
    runWizard('--log-level debug');
    const env = readGeneratedEnv();
    expect(env).toContain('INDEX_SERVER_LOG_LEVEL=debug');
  });

  it('should show help with --help flag', () => {
    try {
      const output = execSync(`node "${WIZARD_SCRIPT}" --help`, EXEC_OPTS).toString();
      expect(output).toContain('setup-wizard');
    } catch (e) {
      // --help may exit with code 0 but execSync might throw
      const output = (e as { stdout?: Buffer }).stdout?.toString() || '';
      expect(output).toContain('setup-wizard');
    }
  });

  it('should include comments and timestamps in .env', () => {
    runWizard('');
    const env = readGeneratedEnv();
    expect(env).toContain('# Index Server Configuration');
    expect(env).toContain('# Generated by setup wizard');
  });
});

describe('Setup Wizard Multi-Target Config', () => {
  const tmpDir = path.join(os.tmpdir(), `wizard-multi-${Date.now()}`);

  afterEach(() => {
    try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch { /* ok */ }
    try { fs.unlinkSync(path.join(ROOT, '.env.generated')); } catch { /* ok */ }
  });

  it('should accept --target copilot-cli flag', () => {
    const output = runWizard('--target copilot-cli');
    // Should run without error; generates env + copilot-cli config
    expect(output).toBeDefined();
  });

  it('should accept --target claude flag', () => {
    const output = runWizard('--target claude');
    expect(output).toBeDefined();
  });

  it('should accept multiple targets', () => {
    const output = runWizard('--target vscode,copilot-cli,claude');
    expect(output).toBeDefined();
  });

  it('should accept --scope global flag', () => {
    const output = runWizard('--scope global');
    expect(output).toBeDefined();
  });

  it('should write VS Code global config to user mcp.json', () => {
    const fakeHome = path.join(os.tmpdir(), `wizard-vscode-global-${Date.now()}`);
    const fakeAppData = path.join(fakeHome, 'AppData', 'Roaming');
    const mcpPath = process.platform === 'win32'
      ? path.join(fakeAppData, 'Code', 'User', 'mcp.json')
      : path.join(fakeHome, '.config', 'Code', 'User', 'mcp.json');

    try {
      fs.mkdirSync(fakeAppData, { recursive: true });

      execSync(
        `node "${WIZARD_SCRIPT}" --non-interactive --target vscode --scope global --write --no-deploy --no-preview`,
        {
          ...EXEC_OPTS,
          cwd: ROOT,
          env: {
            ...process.env,
            HOME: fakeHome,
            USERPROFILE: fakeHome,
            APPDATA: fakeAppData,
          },
        },
      );

      expect(fs.existsSync(mcpPath)).toBe(true);
      expect(fs.existsSync(path.join(path.dirname(mcpPath), 'mcp.json.generated'))).toBe(false);
      const config = parseJsonc(fs.readFileSync(mcpPath, 'utf8')) as {
        servers?: Record<string, { type?: string; command?: string; args?: string[] }>;
      };
      expect(config.servers?.['index-server']?.type).toBe('stdio');
      expect(config.servers?.['index-server']?.command).toBe('node');
      expect(Array.isArray(config.servers?.['index-server']?.args)).toBe(true);
    } finally {
      fs.rmSync(fakeHome, { recursive: true, force: true });
    }
  });

  it('should accept --no-preview flag', () => {
    const output = runWizard('--no-preview');
    // Should suppress preview output
    expect(output).not.toContain('Configuration Preview');
  });

  it('should show preview by default', () => {
    const output = runWizard('');
    expect(output).toContain('Configuration Preview');
  });

  it('should generate copilot-cli format with mcpServers key', () => {
    const output = runWizard('--target copilot-cli');
    // Preview output should contain mcpServers format
    expect(output).toContain('mcpServers');
  });

  it('should generate claude format with mcpServers key', () => {
    const output = runWizard('--target claude');
    expect(output).toContain('mcpServers');
  });

  it('should write config files with --write flag', () => {
    fs.mkdirSync(tmpDir, { recursive: true });
    // Use a temporary root so we write .vscode/mcp.json inside tmpDir
    runWizard(`--root "${tmpDir}" --target vscode --scope repo --write --no-deploy`);
    const mcpPath = path.join(tmpDir, '.vscode', 'mcp.json');
    expect(fs.existsSync(mcpPath)).toBe(true);
    const content = fs.readFileSync(mcpPath, 'utf8');
    expect(content).toContain('"servers"');
  });

  it('should merge existing VS Code mcp.json JSONC and create a backup', () => {
    fs.mkdirSync(path.join(tmpDir, '.vscode'), { recursive: true });
    const mcpPath = path.join(tmpDir, '.vscode', 'mcp.json');
    const existing = `{
      // keep existing servers
      "servers": {
        "existing-server": {
          "type": "stdio",
          "command": "node", // inline JSONC comment
          "args": ["existing.js"],
        },
      },
      "inputs": []
    }`;
    fs.writeFileSync(mcpPath, existing, 'utf8');

    runWizard(`--root "${tmpDir}" --target vscode --scope repo --write --no-deploy --no-preview`);

    const merged = parseJsonc(fs.readFileSync(mcpPath, 'utf8')) as {
      servers?: Record<string, { command?: string; args?: string[] }>;
      inputs?: unknown[];
    };
    expect(merged.servers?.['existing-server']?.command).toBe('node');
    expect(merged.servers?.['index-server']?.command).toBe('node');
    expect(Array.isArray(merged.inputs)).toBe(true);

    const backups = fs.readdirSync(path.dirname(mcpPath)).filter(name => name.startsWith('mcp.json.backup.'));
    expect(backups).toHaveLength(1);
    expect(fs.readFileSync(path.join(path.dirname(mcpPath), backups[0]), 'utf8')).toBe(existing);
  });

  it('should write Copilot CLI config to the .copilot directory', () => {
    const fakeHome = path.join(os.tmpdir(), `wizard-home-${Date.now()}`);
    fs.mkdirSync(fakeHome, { recursive: true });

    execSync(
      `node "${WIZARD_SCRIPT}" --non-interactive --target copilot-cli --write`,
      {
        ...EXEC_OPTS,
        cwd: ROOT,
        env: { ...process.env, HOME: fakeHome, USERPROFILE: fakeHome },
      },
    );

    const mcpPath = path.join(fakeHome, '.copilot', 'mcp-config.json');
    expect(fs.existsSync(mcpPath)).toBe(true);
    const content = fs.readFileSync(mcpPath, 'utf8');
    expect(content).toContain('"mcpServers"');

    fs.rmSync(fakeHome, { recursive: true, force: true });
  });

  it('should merge existing Copilot CLI mcp-config.json and create a backup', () => {
    const fakeHome = path.join(os.tmpdir(), `wizard-home-${Date.now()}`);
    const copilotDir = path.join(fakeHome, '.copilot');
    const mcpPath = path.join(copilotDir, 'mcp-config.json');
    const existing = JSON.stringify({
      mcpServers: {
        'existing-server': {
          command: 'node',
          args: ['existing.js'],
          env: { EXISTING: '1' },
        },
      },
    }, null, 2);

    try {
      fs.mkdirSync(copilotDir, { recursive: true });
      fs.writeFileSync(mcpPath, existing, 'utf8');

      execSync(
        `node "${WIZARD_SCRIPT}" --non-interactive --target copilot-cli --write --no-deploy --no-preview`,
        {
          ...EXEC_OPTS,
          cwd: ROOT,
          env: { ...process.env, HOME: fakeHome, USERPROFILE: fakeHome },
        },
      );

      const merged = JSON.parse(fs.readFileSync(mcpPath, 'utf8')) as {
        mcpServers?: Record<string, { command?: string; args?: string[] }>;
      };
      expect(merged.mcpServers?.['existing-server']?.command).toBe('node');
      expect(merged.mcpServers?.['index-server']?.command).toBe('node');

      const backups = fs.readdirSync(copilotDir).filter(name => name.startsWith('mcp-config.json.backup.'));
      expect(backups).toHaveLength(1);
      expect(fs.readFileSync(path.join(copilotDir, backups[0]), 'utf8')).toBe(existing);
    } finally {
      fs.rmSync(fakeHome, { recursive: true, force: true });
    }
  });

  it('should include help text for --target flag', () => {
    try {
      const output = execSync(`node "${WIZARD_SCRIPT}" --help`, EXEC_OPTS).toString();
      expect(output).toContain('--target');
      expect(output).toContain('--scope');
      expect(output).toContain('--write');
    } catch (e) {
      const output = (e as { stdout?: Buffer }).stdout?.toString() || '';
      expect(output).toContain('--target');
    }
  });
});

describe('Setup Wizard Next Steps — Build Step Skip', () => {
  const distFile = path.join(ROOT, 'dist', 'server', 'index-server.js');

  afterEach(() => {
    try { fs.unlinkSync(path.join(ROOT, '.env.generated')); } catch { /* ok */ }
  });

  it('should skip "Build the server" step when dist exists', () => {
    // In a dev repo after `npm run build`, dist/server/index-server.js exists
    if (!fs.existsSync(distFile)) {
      console.log('dist not built — skipping (run npm run build first)');
      return;
    }
    const output = runWizard('');
    expect(output).toContain('Next Steps');
    expect(output).not.toContain('Build the server');
    expect(output).not.toContain('npm run build');
  });

  it('should NOT show "Build the server" step when --root is a data-only directory (#260)', () => {
    // Issue #260: when --root points to a data-only directory (no package.json),
    // the build prompt is unreachable (`npm run build` ENOENTs there). The wizard
    // is using a packaged runtime — there is nothing for the user to build at the
    // data root. Show the packaged-runtime info banner instead.
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'wizard-test-'));
    try {
      const output = runWizard(`--root "${tmpRoot}" --no-deploy`);
      expect(output).not.toContain('Build the server');
      expect(output).not.toContain('npm run build');
      // Should mention the packaged runtime so the user knows nothing more is needed.
      expect(output).toContain('packaged runtime');
    } finally {
      fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
  });

  it('should number steps correctly when build step is skipped', () => {
    if (!fs.existsSync(distFile)) {
      console.log('dist not built — skipping');
      return;
    }
    const output = runWizard('');
    // Without build step, first step should be "1. Copy generated config" or "1. Config files"
    // and dashboard should be "2. Open the dashboard"
    expect(output).toMatch(/1\.\s+(Copy generated config|Config files have been written)/);
    expect(output).toMatch(/2\.\s+Open the dashboard/);
  });

  it('should number steps correctly when --root is a data-only directory (#260)', () => {
    // Issue #260: with packaged runtime there is no build step, so step 1 is the
    // copy/config step and step 2 is the dashboard URL.
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'wizard-test-'));
    try {
      const output = runWizard(`--root "${tmpRoot}" --no-deploy`);
      expect(output).toMatch(/1\.\s+(Copy generated config|Config files have been written)/);
      expect(output).toMatch(/2\.\s+Open the dashboard/);
      expect(output).not.toMatch(/Build the server/);
    } finally {
      fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
  });

  it('should show semantic search step for enhanced profile regardless of dist', () => {
    const output = runWizard('--profile enhanced');
    expect(output).toContain('First-time semantic search');
    expect(output).toContain('MiniLM model');
  });
});

describe('Setup Wizard TLS Certificate Integration', () => {
  it('should generate certs for enhanced profile using the packaged script path', () => {
    if (!hasOpenSsl()) {
      console.log('OpenSSL not available — skipping enhanced profile cert integration test');
      return;
    }

    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'wizard-tls-'));
    try {
      const result = spawnSync(
        process.execPath,
        [
          WIZARD_SCRIPT,
          '--non-interactive',
          '--profile',
          'enhanced',
          '--root',
          tmpRoot,
          '--no-deploy',
          '--no-preview',
        ],
        {
          cwd: ROOT,
          encoding: 'utf8',
          timeout: 60_000,
          env: { ...process.env, HOME: os.tmpdir(), USERPROFILE: os.tmpdir() },
        },
      );

      const combinedOutput = `${result.stdout}\n${result.stderr}`;
      expect(result.status, combinedOutput).toBe(0);
      expect(combinedOutput).not.toContain('MODULE_NOT_FOUND');
      expect(combinedOutput).not.toContain('Cannot find module');
      expect(fs.existsSync(path.join(tmpRoot, 'certs', 'ca.crt'))).toBe(true);
      expect(fs.existsSync(path.join(tmpRoot, 'certs', 'server.crt'))).toBe(true);
      expect(fs.existsSync(path.join(tmpRoot, 'certs', 'server.key'))).toBe(true);
    } finally {
      fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
  }, 90_000);
});

describe('Setup Wizard Runtime Deployment', () => {
  const tmpDir = path.join(os.tmpdir(), `wizard-deploy-${Date.now()}`);

  afterEach(() => {
    try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch { /* ok */ }
  });

  it('should deploy runtime when root differs from package root', () => {
    const output = runWizard(`--root "${tmpDir}" --no-preview`, DEPLOY_EXEC_OPTS);
    expect(output).toContain('Deploying runtime');
    expect(output).toContain('Runtime deployed');
    // dist/ should exist at target
    expect(fs.existsSync(path.join(tmpDir, 'dist', 'server', 'index-server.js'))).toBe(true);
    // schemas/ should exist
    expect(fs.existsSync(path.join(tmpDir, 'schemas'))).toBe(true);
  }, DEPLOY_TEST_TIMEOUT_MS);

  it('should skip deploy when root equals package root', () => {
    const output = runWizard('--no-preview');
    expect(output).not.toContain('Deploying runtime');
  });

  it('should skip "Build the server" step after successful deploy', () => {
    const output = runWizard(`--root "${tmpDir}" --no-preview`, DEPLOY_EXEC_OPTS);
    expect(output).toContain('Runtime deployed');
    // Next steps should NOT show build step since dist was just deployed
    expect(output).not.toContain('Build the server');
    expect(output).not.toContain('npm run build');
  }, DEPLOY_TEST_TIMEOUT_MS);
});

describe('Setup Wizard Runtime Deployment Timeouts', () => {
  const wizardSource = fs.readFileSync(WIZARD_SCRIPT, 'utf8');
  const smokeSource = fs.readFileSync(path.join(ROOT, 'scripts', 'ci', 'clean-install-smoke.mjs'), 'utf8');

  it('should allow the runtime npm install timeout to be overridden by environment', () => {
    expect(wizardSource).toContain('INDEX_SERVER_SETUP_INSTALL_TIMEOUT_MS');
    expect(wizardSource).toContain('parsePositiveTimeout');
    expect(wizardSource).toContain('DEPLOY_INSTALL_TIMEOUT_MS');
  });

  it('should give Windows clean-install deployment enough time for nested npm install', () => {
    expect(wizardSource).toContain('IS_WINDOWS ? 420_000 : 120_000');
    expect(smokeSource).toContain('runtimeDeployInstallTimeoutMs = isWindows ? 420_000 : 180_000');
    expect(smokeSource).toContain('INDEX_SERVER_SETUP_INSTALL_TIMEOUT_MS');
    expect(smokeSource).toContain('setupTimeoutMs = isWindows ? 600_000 : 240_000');
  });
});

describe('Setup Wizard Launch Resolution', () => {
  const dataDir = path.join(os.tmpdir(), `wizard-launch-${Date.now()}`);

  afterEach(() => {
    try { fs.rmSync(dataDir, { recursive: true, force: true }); } catch { /* ok */ }
    try { fs.unlinkSync(path.join(ROOT, '.env.generated')); } catch { /* ok */ }
  });

  it('should use absolute path to dist/ when --root is a data-only directory', () => {
    fs.mkdirSync(dataDir, { recursive: true });
    runWizard(`--root "${dataDir}" --target vscode --scope repo --write --no-deploy`);
    const mcpPath = path.join(dataDir, '.vscode', 'mcp.json');
    expect(fs.existsSync(mcpPath)).toBe(true);
    const content = fs.readFileSync(mcpPath, 'utf8');
    // Should NOT contain bare relative dist path since dataDir has no dist/
    expect(content).not.toContain('"args": ["dist/server/index-server.js"]');
    // Should contain absolute path to the actual dist or npx command
    const hasAbsoluteDist = content.includes('dist/server/index-server.js') && !content.includes('"args": ["dist/server/index-server.js"]');
    const hasNpx = content.includes('"command": "npx"');
    expect(hasAbsoluteDist || hasNpx).toBe(true);
  });

  it('should use relative dist path when running from dev checkout root', () => {
    // When root = ROOT (the repo itself with dist/), command should be node + relative path
    const output = runWizard('');
    // Preview output should contain the relative dist path since ROOT has dist/
    expect(output).toContain('dist/server/index-server.js');
  });

  it('should generate working copilot-cli config for external data directory', () => {
    fs.mkdirSync(dataDir, { recursive: true });
    const output = runWizard(`--root "${dataDir}" --target copilot-cli --no-deploy`);
    // Preview should show mcpServers with absolute path or npx, not relative dist
    expect(output).toContain('mcpServers');
    // The args should not be the bare relative path
    const previewSection = output.split('copilot-cli')[1] || '';
    if (previewSection.includes('dist/server/index-server.js')) {
      // If it has dist path, it should be absolute (contains the ROOT path)
      expect(previewSection).toContain(ROOT.replace(/\\/g, '/'));
    }
  });

  it('should use a portable VS Code config for data-only roots', () => {
    fs.mkdirSync(dataDir, { recursive: true });
    runWizard(`--root "${dataDir}" --target vscode --scope repo --write --no-deploy`);
    const mcpPath = path.join(dataDir, '.vscode', 'mcp.json');
    const content = fs.readFileSync(mcpPath, 'utf8');
    expect(content).toContain(ROOT.replace(/\\/g, '/'));
    expect(content).not.toContain(`"args": ["dist/server/index-server.js"]`);
  });
});


describe('Certificate Generation', () => {
  const certDir = path.join(os.tmpdir(), `cert-test-${Date.now()}`);
  const CERT_SCRIPT = path.join(ROOT, 'scripts', 'build', 'generate-certs.mjs');

  afterEach(() => {
    try { fs.rmSync(certDir, { recursive: true, force: true }); } catch { /* ok */ }
  });

  it('should generate CA and server certificates', () => {
    let hasOpenssl = false;
    try { execSync('openssl version', { stdio: 'pipe' }); hasOpenssl = true; } catch { /* ok */ }
    // Fallback: check well-known Git-bundled OpenSSL on Windows
    if (!hasOpenssl && process.platform === 'win32') {
      const gitSslDir = 'C:\\Program Files\\Git\\usr\\bin';
      if (fs.existsSync(path.join(gitSslDir, 'openssl.exe'))) {
        process.env.PATH = `${gitSslDir}${path.delimiter}${process.env.PATH}`;
        hasOpenssl = true;
      }
    }
    if (!hasOpenssl) {
      console.log('OpenSSL not available — skipping cert generation test');
      return;
    }

    execSync(
      `node "${CERT_SCRIPT}" --hostname localhost --days 1 --output "${certDir}"`,
      { ...EXEC_OPTS, timeout: 30_000 }
    );

    expect(fs.existsSync(path.join(certDir, 'ca.crt'))).toBe(true);
    expect(fs.existsSync(path.join(certDir, 'ca.key'))).toBe(true);
    expect(fs.existsSync(path.join(certDir, 'server.crt'))).toBe(true);
    expect(fs.existsSync(path.join(certDir, 'server.key'))).toBe(true);
  });

  it('should create certs with correct SAN entries', () => {
    let hasOpenssl = false;
    try { execSync('openssl version', { stdio: 'pipe' }); hasOpenssl = true; } catch { /* ok */ }
    // Fallback: check well-known Git-bundled OpenSSL on Windows
    if (!hasOpenssl && process.platform === 'win32') {
      const gitSslDir = 'C:\\Program Files\\Git\\usr\\bin';
      if (fs.existsSync(path.join(gitSslDir, 'openssl.exe'))) {
        process.env.PATH = `${gitSslDir}${path.delimiter}${process.env.PATH}`;
        hasOpenssl = true;
      }
    }
    if (!hasOpenssl) return;

    execSync(
      `node "${CERT_SCRIPT}" --hostname myhost.local --days 1 --output "${certDir}"`,
      { ...EXEC_OPTS, timeout: 30_000 }
    );

    const certInfo = execSync(
      `openssl x509 -in "${path.join(certDir, 'server.crt')}" -text -noout`,
      { stdio: 'pipe' }
    ).toString();

    expect(certInfo).toContain('myhost.local');
    expect(certInfo).toContain('127.0.0.1');
  });
});
