import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';

/**
 * Regression guard for #544.
 *
 * `scripts/build/generate-schemas.mjs` stamped `new Date().toISOString()` into
 * `schemas/manifest.json` and `schemas/index-server.code-schema.json`, which are
 * tracked. Because `npm run build` regenerates them, any two branches that ran a
 * build conflicted on those files by construction -- #530 sat at CONFLICTING for
 * four days over nothing but a timestamp diff.
 *
 * These tests fail if a wall-clock timestamp is reintroduced into a build
 * generator or into the tracked artifacts themselves.
 */

const ROOT = process.cwd();
const BUILD_DIR = path.join(ROOT, 'scripts', 'build');

// Tracked, regenerated by `npm run build` -- the artifacts that actually collided.
const TRACKED_ARTIFACTS = [
  path.join('schemas', 'manifest.json'),
  path.join('schemas', 'index-server.code-schema.json'),
];

function buildGenerators(): string[] {
  return fs.readdirSync(BUILD_DIR)
    .filter(f => f.endsWith('.mjs'))
    .map(f => path.join(BUILD_DIR, f));
}

describe('#544 build artifacts carry no wall-clock timestamp', () => {
  it('has build generators to scan (guards against a vacuous pass)', () => {
    expect(buildGenerators().length).toBeGreaterThan(0);
  });

  it('no build generator stamps a wall-clock timestamp into its output', () => {
    const offenders: string[] = [];
    for (const file of buildGenerators()) {
      const src = fs.readFileSync(file, 'utf8');
      // `generatedAt:` bound to a live clock read, on the same line or the next.
      if (/generatedAt\s*:\s*new Date\(\)/.test(src)) {
        offenders.push(path.relative(ROOT, file));
      }
    }
    expect(offenders).toEqual([]);
  });

  it('tracked schema artifacts contain no generatedAt key', () => {
    for (const rel of TRACKED_ARTIFACTS) {
      const full = path.join(ROOT, rel);
      if (!fs.existsSync(full)) continue; // not built in this checkout
      const parsed = JSON.parse(fs.readFileSync(full, 'utf8'));
      expect(Object.keys(parsed), `${rel} must not embed a build timestamp`)
        .not.toContain('generatedAt');
    }
  });

  it('tracked schema artifacts exist and are non-trivial', () => {
    // Pairs with the previous test: without this, deleting the artifacts would
    // make the generatedAt assertion pass vacuously.
    const present = TRACKED_ARTIFACTS.filter(rel => fs.existsSync(path.join(ROOT, rel)));
    expect(present.length).toBe(TRACKED_ARTIFACTS.length);
    for (const rel of present) {
      const parsed = JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
      expect(Object.keys(parsed).length).toBeGreaterThan(1);
    }
  });
});

/**
 * Regression guard for #558 / #555 P2.4.
 *
 * The code model used to stamp `"line": N` onto every declaration. That made
 * the tracked artifact churn on every unrelated edit above a declaration --
 * 221 of the 226 changed rows in #554's diff were pure renumbering -- which
 * both conflicted concurrent branches and camouflaged the real shape changes
 * that the CI freshness gate exists to surface.
 *
 * Line numbers are now opt-in (`--line-numbers`). These tests fail if that
 * default is flipped back.
 */
describe('#558 code schema carries no declaration line numbers', () => {
  const CODE_SCHEMA = path.join(ROOT, 'schemas', 'index-server.code-schema.json');
  const MANIFEST = path.join(ROOT, 'schemas', 'manifest.json');

  it('the artifacts under test exist (guards against a vacuous pass)', () => {
    expect(fs.existsSync(CODE_SCHEMA), 'schemas/index-server.code-schema.json').toBe(true);
    expect(fs.existsSync(MANIFEST), 'schemas/manifest.json').toBe(true);
  });

  it('manifest records lineNumbers: false', () => {
    const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
    expect(manifest.codeModel?.features?.lineNumbers).toBe(false);
  });

  it('no declaration in the code model carries a line field', () => {
    const model = JSON.parse(fs.readFileSync(CODE_SCHEMA, 'utf8'));
    const offenders: string[] = [];

    // Walk every object; a *key* named `line` is the injected field. A property
    // whose `name` VALUE is "line" is ordinary source (7 such declarations
    // exist) and must not be flagged -- so this checks keys, not values.
    const walk = (node: unknown, trail: string): void => {
      if (Array.isArray(node)) {
        node.forEach((child, i) => walk(child, `${trail}[${i}]`));
        return;
      }
      if (node === null || typeof node !== 'object') return;
      for (const [key, value] of Object.entries(node as Record<string, unknown>)) {
        if (key === 'line') offenders.push(`${trail}.line`);
        walk(value, `${trail}.${key}`);
      }
    };
    walk(model, '$');

    // Falsification anchor: the walker must actually reach declarations.
    expect(model.files.length, 'code model has files to walk').toBeGreaterThan(100);
    expect(offenders.slice(0, 5)).toEqual([]);
  });
});
